name: Build bs-platform-js
on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * *' # every day at midnight utc

jobs:
  run:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ocaml-version: ["4.06.1"]
        node-version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout BuckleScript repo
        uses: actions/checkout@v2
        with:
          repository: BuckleScript/bucklescript
          path: bucklescript

      - run: git submodule update --init && ./scripts/buildocaml.js
        working-directory: bucklescript

      - run: ./scripts/ninja.js config && ./scripts/ninja.js build
        working-directory: bucklescript

      - run: node scripts/install.js
        working-directory: bucklescript

      - run: yarn link
        working-directory: bucklescript

      - run: BS_PLAYGROUND=../../main/bundle ./scripts/repl.js -prepublish
        working-directory: bucklescript

      - name: Test — print Sys.ocaml_version
        run: node -e "require('./exports.js'); eval(ocaml.compile('Js.log Sys.ocaml_version').js_code)"
        working-directory: main/bundle

      - name: Build 3rd party packages
        run: ./scripts/generate_packages.js
        working-directory: main

      - name: Test — 3rd party packages
        run: |
          node -e "
          require('./bundle/exports.js');
          require('./packages/reason-react/cmij.js');
          var assert = require('assert');
          assert(
            reason
              .compile('let t = ReactDOMRe.renderToElementWithId(<div />);')
              .js_code.indexOf('ReactDOMRe.renderToElementWithId') > 0
          );"
        working-directory: main

      - name: Archive bundle artifacts
        uses: actions/upload-artifact@v1
        with:
          name: bs-platform-js
          path: main/bundle

      - name: Archive packages artifacts
        uses: actions/upload-artifact@v1
        with:
          name: packages
          path: main/packages

